### ISSUE TITLE
theres nothing here yet error

### ISSUE THREAD

**Issue by wxce** [ellieeet123/end-securly#2]
i get a theres nothing here yet error while using it

**Comment by ellieeet123** [comment]
Just checked that, seems like my heroku account got suspended lol. I'll make a new account and a new proxy in a bit once i have some time

**Comment by twelvthe** [comment]
do we have an eta?, im trying to not do school work 😆:trollface:

**Comment by ellieeet123** [comment]
Should be good to go now. If it doesn't work, try either doing `CTRL`+`SHIFT`+`R` on the site you're trying to activate the bookmarklet from, or go to a new site that you've never run the bookmarklet from and activate it there.
